:HEADER:
#+TITLE: THE PSALTER, OR PSALMS of DAVID
#+SUBTITLE: Pointed as they are to be sung or said in Churches
#+DATE: 1662
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LANGUAGE: en
#+OPTIONS: html-postamble:nil
#+LATEX: \setlength\parindent{0pt}
#+SETUPFILE: ./jacmoe-latex-standard-setup.org
:END:
#+begin_export LaTeX
\pagebreak
#+end_export

* THE FIRST DAY
** MORNING PRAYER
*** PSALM 1
1 Beatus vir, qui non abiit. BLESSED is the man that hath not walked in the counsel of the ungodly, nor stood in the way of sinners: and hath not sat in the seat of the scornful;
2 But his delight is in the law of the Lord: and in his law will he exercise himself day and night.
3 And he shall be like a tree planted by the water-side: that will bring forth his fruit in due season.
4 His leaf also shall not wither: and look, whatsoever he doeth, it shall prosper.
5 As for the ungodly, it is not so with them: but they are like the chaff, which the wind scattereth away from the face of the earth.
6 Therefore the ungodly shall not be able to ſtand in the judgment: neither the sinners in the congregation of the righteous.
7 But the Lord knoweth the way of the righteous: and the way of the ungodly shall perish.

# Local Variables:
# flycheck-disabled-checkers: (proselint)
# End:
