:HEADER:
#+TITLE: THE PSALTER, OR PSALMS of DAVID
#+SUBTITLE: Pointed as they are to be sung or said in Churches
#+AUTHOR: as printed by John Baskerville
#+DATE: 1762
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+LANGUAGE: en
#+OPTIONS: html-postamble:nil
#+LATEX: \setlength\parindent{0pt}
#+SETUPFILE: ./jacmoe-latex-standard-setup.org
:END:

#+begin_export LaTeX
\pagebreak
#+end_export

* THE FIRST DAY
** MORNING PRAYER
*** PSALM 1 : Beatus vir, qui non abiit
#+begin_verse
BLESSED is the man that hath not walked in the counsel of the ungodly, nor stood in the way of sinners: and hath not sat in the seat of the scornful;
2 But his delight is in the law of the Lord: and in his law will he exercise himself day and night.
3 And he shall be like a tree planted by the water-side: that will bring forth his fruit in due season.
4 His leaf also shall not wither: and look, whatsoever he doeth, it shall prosper.
5 As for the ungodly, it is not so with them: but they are like the chaff, which the wind scattereth away from the face of the earth.
6 Therefore the ungodly shall not be able to stand in the judgment: neither the sinners in the congregation of the righteous.
7 But the Lord knoweth the way of the righteous: and the way of the ungodly shall perish.
#+end_verse
*** PSALM 2 : Quare fremuerunt?
#+begin_verse
WHY do the heathen so furiously rage together: and why do the people imagine a vain thing?
2 The kings of the earth stand up, and the rulers take counsel together: against the Lord, and against his Anointed.
3 Let us break their bonds asunder: and cast away their cords from us.
4 He that dwelleth in heaven shall laugh them to scorn: the Lord shall have them in derision.
5 Then shall he speak unto them in his wrath: and vex them in his sore displeasure.
6 Yet I have set my King: upon my holy hill of Sion.
7 I will preach the law, whereof the Lord hath said unto me: Thou art my Son, this day have I begotten thee.
8 Desire of me, and I shall give thee the heathen for thine inheritance: and the utmost parts of the earth for thy possession.
9 Thou shalt bruise them with a rod of iron: and break them in pieces like a potter’s vessel.
10 Be wise now therefore, O ye kings: be learned, ye that are judges of the earth.
11 Serve the Lord in fear: and rejoice unto him with reverence.
12 Kiss the Son, lest he be angry, and so ye perish from the right way: if his wrath be kindled, (yea, but a little,) blessed are all they that put their trust in him.
#+end_verse
*** Psalm 3 : Domine, quid multiplicati?
#+begin_verse
LORD, how are they increased that trouble me: many are they that rise against me.
2 Many one there be that say of my soul: There is no help for him in his God.
3 But thou, O Lord, art my defender: thou art my worship, and the lifter up of my head.
4 I did call upon the Lord with my voice: and he heard me out of his holy hill.
5 I laid me down and slept, and rose up again: for the Lord sustained me.
6 I will not be afraid for ten thousands of the people: that have set themselves against me round about.
7 Up, Lord, and help me, O my God: for thou smitest all mine enemies upon the cheekbone; thou hast broken the teeth of the ungodly.
8 Salvation belongeth unto the Lord: and thy blessing is upon thy people
#+end_verse
*** Psalm 4 : Cum invocarem.
#+begin_verse
HEAR me when I call, O God of my righteousness: thou hast set me at liberty when I was in trouble; have mercy upon me, and hearken unto my prayer.
2 O ye sons of men, how long will ye blaspheme mine honour: and have such pleasure in vanity, and seek after leasing?
3 Know this also, that the Lord hath chosen to himself the man that is godly: when I call upon the Lord, he will hear me.
4 Stand in awe, and sin not: commune with your own heart, and in your chamber, and be still.
5 Offer the sacrifice of righteousness: and put your trust in the Lord.
6 There be many that say: Who will shew us any good?
7 Lord, lift thou up: the light of thy countenance upon us.
8 Thou hast put gladness in my heart: since the time that their corn and wine and oil increased.
9 I will lay me down in peace, and take my rest: for it is thou, Lord, only, that makest me dwell in safety.
#+end_verse
*** Psalm 5 : Verba mea auribus.
#+begin_verse
PONDER my words, O Lord: consider my meditation
2 O hearken thou unto the voice of my calling, my King, and my God: for unto thee will I make my prayer.
3 My voice shalt thou hear betimes, O Lord: early in the morning will I direct my prayer unto thee, and will look up.
4 For thou art the God that hast no pleasure in wickedness: neither shall any devil dwell with thee.
5 Such as be foolish shall not stand in thy sight: for thou hatest all of them that work vanity.
6 Thou shalt destroy them that speak leasing: the Lord will abhor both the bloodthirsty and deceitful man.
7 But as for me, I will come into thine house, even upon the multitude of thy mercy: and in thy fear will I worship toward thy holy temple.
8 Lead me, O Lord, in thy righteousness, because of mine enemies: make thy way plain before my face.
9 For there is no faithfulness in his mouth: their inward parts are very wickedness.
10 Their throat is an open sepulchre: they flatter with their tongue.
11 Destroy thou them, O God; let them perish through their own imaginations: cast them out in the multitude of their ungodliness; for they have rebelled against thee.
12 And let all them that put their trust in thee rejoice: they shall ever be giving of thanks, because thou defendest them; they that love thy Name shall be joyful in thee;
13 For thou, Lord, wilt give thy blessing unto the righteous: and with thy favourable kindness wilt thou defend him as with a shield.
#+end_verse
** EVENING PRAYER
*** Psalm 6 : Domine, one in furore.
#+begin_verse
O Lord, rebuke me not in thine indignation: neither chasten me in thy displeasure.
2 Have mercy upon me, O Lord, for I am weak: O Lord, heal me, for my bones are vexed.
3 My soul also is sore troubled: but, Lord, how long wilt thou punish me?
4 Turn thee, O Lord, and deliver my soul: O save me for thy mercy’s sake.
5 For in death no man remembereth thee: and who will give thee thanks in the pit?
6 I am weary of my groaning; every night wash I my bed: and water my couch with my tears.
7 My beauty is gone for very trouble: and worn away because of all mine enemies.
8 Away from me, all ye that work vanity: for the Lord hath heard the voice of my weeping.
9 The Lord hath heard my petition: the Lord will receive my prayer.
10 All mine enemies shall be confounded, and sore vexed: they shall be turned back, and put to shame suddenly.
#+end_verse
*** Psalm 7 : Domine, Deus meus.
#+begin_verse
Lord my God, in thee have I put my trust: save me from all them that persecute me, and deliver me;
2 Lest he devour my soul, like a lion, and tear it in pieces: while there is none to help.
3 O Lord my God, if I have done any such thing: or if there be any wickedness in my hands;
4 If I have rewarded evil unto him that dealt friendly with me: (yea, I have delivered him that without any cause is mine enemy;)
5 Then let mine enemy persecute my soul, and take me: yea, let him tread my life down upon the earth, and lay mine honour in the dust.
6 Stand up, O Lord, in thy wrath, and lift up thyself, because of the indignation of mine enemies: arise up for me in the judgment that thou hast commanded.
7 And so shall the congregation of the people come about thee: for their sakes therefore lift up thyself again.
8 The Lord shall judge the people; give sentence with me, O Lord: according to my righteousness, and according to the innocency that is in me.
9 O let the wickedness of the ungodly come to an end: but guide thou the just.
10 For the righteous God: trieth the very hearts and reins.
11 My help cometh of God: who preserveth them that are true of heart.
12 God is a righteous Judge, strong, and patient: and God is provoked every day.
13 If a man will not turn, he will whet his sword: he hath bent his bow, and made it ready.
14 He hath prepared for him the instruments of death: he ordaineth his arrows against the persecutors.
15 Behold, he travaileth with mischief: he hath conceived sorrow, and brought forth ungodliness.
16 He hath graven and digged up a pit: and is fallen on himself into the destruction that he made for other.
17 For his travail shall come upon his own head: and his wickedness shall fall on his own pate.
18 I will give thanks unto the Lord, according to his righteousness: and I will praise the Name of the Lord most High.
#+end_verse
*** Psalm 8 : Domine, Dominus noster.
#+begin_verse
O Lord our Governor, how excellent is thy Name in all the world: thou hast set thy glory above the heavens!
2 Out of the mouth of very babes and sucklings hast thou ordained strength, because of thine enemies: that thou mightest still the enemy and the avenger.
3 For I will consider thy heavens, even the works of thy fingers: the moon and the stars, which thou hast ordained.
4 What is man, that thou art mindful of him: and the son of man, that thou visitest him?
5 Thou madest him lower than the angels: to crown him with glory and worship.
6 Thou makest him to have dominion of the works of thy hands: and thou hast put all things in subjection under his feet;
7 All sheep and oxen: yea, and the beasts of the field;
8 The fowls of the air, and the fishes of the sea: and whatsoever walketh through the paths of the seas.
9 O Lord our Governor: how excellent is thy Name in all the world!
#+end_verse
* THE SECOND DAY
** MORNING PRAYER
*** Psalm 9 : Confitebor tibi.
#+begin_verse
I Will give thanks unto thee, O Lord, with my whole heart: I will speak of all thy marvellous works.
2 I will be glad and rejoice in thee: yea, my songs will I make of thy Name, O thou most Highest.
3 While mine enemies are driven back: they shall fall and perish at thy presence.
4 For thou hast maintained my right, and my cause: thou art set in the throne that judgest right.
5 Thou hast rebuked the heathen, and destroyed the ungodly: thou hast put out their name for ever and ever.
6 O thou enemy, destructions are come to a perpetual end: even as the cities which thou hast destroyed; their memorial is perished with them.
7 But the Lord shall endure for ever: he hath also prepared his seat for judgment.
8 For he shall judge the world in righteousness: and minister true judgment unto the people.
9 The Lord also will be a defence for the oppressed: even a refuge in due time of trouble.
10 And they that know thy Name, will put their trust in thee: for thou, Lord, hast never failed them that seek thee.
11 O praise the Lord which dwelleth in Sion: shew the people of his doings.
12 For when he maketh inquisition for blood, he remembereth them: and forgetteth not the complaint of the poor.
13 Have mercy upon me, O Lord; consider the trouble which I suffer of them that hate me: thou that liftest me up from the gates of death.
14 That I may shew all thy praises within the ports of the daughter of Sion: I will rejoice in thy salvation.
15 The heathen are sunk down in the pit that they made: in the same net which they hid privily, is their foot taken.
16 The Lord is known to execute judgment: the ungodly is trapped in the work of his own hands.
17 The wicked shall be turned into hell: and all the people that forget God.
18 For the poor shall not always be forgotten: the patient abiding of the meek shall not perish for ever.
19 Up, Lord, and let not man have the upper hand: let the heathen be judged in thy sight.
20 Put them in fear, O Lord: that the heathen may know themselves to be but men.
#+end_verse
*** Psalm 10 : Ut quid, Domine?
#+begin_verse
WHY standest thou so far off, O Lord: and hidest thy face in the needful time of trouble?
2 The ungodly for his own lust doth persecute the poor: let them be taken in the crafty wiliness that they have imagined.
3 For the ungodly hath made boast of his own heart's desire: and speaketh good of the covetous, whom God abhorreth.
4 The ungodly is so proud, that he careth not for God; neither is God in all his thoughts.
5 His ways are always grievous: thy judgments are far above out of his sight, and therefore defieth he all his enemies.
6 For he hath said in his heart, Tush, I shall never be cast down: there shall no harm happen unto me.
7 His mouth is full of cursing, deceit, and fraud: under his tongue is ungodliness and vanity.
8 He sitteth lurking in the thievish corners of the streets: and privily in his lurking dens doth he murder the innocent; his eyes are set against the poor.
9 For he lieth waiting secretly, even as a lion lurketh he in his den: that he may ravish the poor.
10 He doth ravish the poor: when he getteth him into his net.
11 He falleth down, and humbleth himself: that the congregation of the poor may fall into the hands of his captains.
12 He hath said in his heart, Tush, God hath forgotten: he hideth away his face, and he will never see it.
13 Arise, O Lord God, and lift up thine hand: forget not the poor.
14 Wherefore should the wicked blaspheme God: while he doth say in his heart, Tush,thou God carest not for it.
15 Surely thou hast seen it: for thou beholdest ungodliness and wrong.
16 That thou mayest take the matter into thy hand: the poor committeth himself unto thee; for thou art the helper of the friendless.
17 Break thou the power of the ungodly and malicious: take away his ungodliness, and thou shalt find none.
18 The Lord is King for ever and ever: and the heathen are perished out of the land.
19 Lord, thou hast heard the desire of the poor: thou preparest their heart, and thine ear hearkeneth thereto;
20 To help the fatherless and poor unto their right: that the man of the earth be no more exalted against them.
#+end_verse
*** Psalm 11 : In Domino confido.
#+begin_verse
IN the Lord put I my trust: how say ye then to my soul, that she should flee as a bird unto the hill?
2 For lo, the ungodly bend their bow, and make ready their arrows within the quiver: that they may privily shoot at them which are true of heart.
3 For the foundations will be cast down: and what have the righteous done?
4 The Lord is in his holy temple: the Lord’s seat is in heaven.
5 His eyes consider the poor: and his eyelids try the children of men.
6 The Lord alloweth the righteous: but the ungodly, and him that delighteth in wickedness, doth his soul abhor.
7 Upon the ungodly he shall rain snares, fire and brimstone, storm and tempest: this shall be their portion to drink.
8 For the righteous Lord loveth righteousness: his countenance will behold the thing that is just.
#+end_verse
** EVENING PRAYER
*** Psalm 12 : Salvum me fac.
#+begin_verse
HELP me, Lord, for there is not one godly man left: for the faithful are minished from among the children of men.
2 They talk of vanity every one with his neighbour: they do but flatter with their lips, and dissemble in their double heart.
3 The Lord shall root out all deceitful lips: and the tongue that speaketh proud things;
4 Which have said, With our tongue will we prevail: we are they that ought to speak; Who is lord over us?
5 Now for the comfortless trouble's sake of the needy: and because of the deep sighing of the poor;
6 I will up, saith the Lord: and will help every one from him that swelleth against him, and will set him at rest.
7 The words of the Lord are pure words: even as the silver, which from the earth is tried, and purified seven times in the fire.
8 Thou shalt keep them, O Lord: thou shalt preserve him from this generation for ever.
9 The ungodly walk on every side: when they are exalted, the children of men are put to rebuke.
#+end_verse
*** Psalm 13 : Usque quo, Domine?
#+begin_verse
HOW long wilt thou forget me, O Lord, for ever: how long wilt thou hide thy face from me?
2 How long shall I seek counsel in my soul, and be so vexed in my heart: how long shall mine enemies triumph over me?
3 Consider, and hear me, O Lord my God: lighten mine eyes, that I sleep not in death.
4 Lest mine enemy say, I have prevailed against him: for if I be cast down, they that trouble me will rejoice at it.
5 But my trust is in thy mercy: and my heart is joyful in thy salvation.
6 I will sing of the Lord, because he hath dealt so lovingly with me: yea, I will praise the Name of the Lord most Highest.
#+end_verse
*** Psalm 14 : Dixit insipiens.
#+begin_verse
THE fool hath said in his heart: There is no God.
2 They are corrupt, and become abominable in their doings: there is none that doeth good, no not one.
3 The Lord looked down from heaven upon the children of men: to see if there were any that would understand, and seek after God.
4 But they are all gone out of the way, they are altogether become abominable: there is none that doeth good, no not one.
5 Their throat is an open sepulchre; with their tongues have they deceived: the poison of asps is under their lips.
6 Their mouth is full of cursing and bitterness: their feet are swift to shed blood.
7 Destruction and unhappiness is in their ways, and the way of peace have they not known; there is no fear of God before their eyes.
8 Have they no knowledge, that they are all such workers of mischief: eating up my people as it were bread, and call not upon the Lord?
9 There were they brought in great fear, even where no fear was: for God is in the generation of the righteous.
10 As for you, ye have made a mock at the counsel of the poor: because he putteth his trust in the Lord.
11 Who shall give salvation unto Israel out of Sion? When the Lord turneth the captivity of his people: then shall Jacob rejoice, and Israel shall be glad.
#+end_verse
* THE THIRD DAY
** MORNING PRAYER
*** Psalm 15 : Domine, quis habitabit?
#+begin_verse
LORD, who shall dwell in thy tabernacle: or who shall rest upon thy holy hill?
2 Even he that leadeth an uncorrupt life: and doeth the thing which is right, and speaketh the truth from his heart.
3 He that hath used no deceit in his tongue, nor done evil to his neighbour: and hath not slandered his neighbour.
4 He that setteth not by himself, but is lowly in his own eyes: and maketh much of them that fear the Lord.
5 He that sweareth unto his neighbour, and disappointeth him not: thou it were to his own hindrance.
6 He that hath not given his money upon usury: nor taken reward against the innocent.
7 Whoso doeth these things: shall never fall.
#+end_verse
*** Psalm 16 : Conserva me, Domine.
#+begin_verse
PRESERVE me, O God: for in thee have I put my trust.
2 O my soul, thou hast said unto the Lord: Thou art my God; my goods are nothing unto thee.
3 All my delight is upon the saints, that are in the earth: and upon such as excel in virtue.
4 But they that run after another god: shall have great trouble.
5 Their drink-offerings of blood will I not offer: neither make mention of their names within my lips.
6 The Lord himself is the portion of mine inheritance, and of my cup: thou shalt maintain my lot.
7 The lot is fallen unto me in a fair ground: yea, I have a goodly heritage.
8 I will thank the Lord for giving me warning: my reins also chasten me in the nightseason.
9 I have set God always before me: for he is on my right hand, therefore I shall not fall.
10 Wherefore my heart was glad, and my glory rejoiced: my flesh also shall rest in hope.
11 For why? thou shalt not leave my soul in hell: neither shalt thou suffer thy Holy One to see corruption.
12 Thou shalt shew me the path of life; in thy presence is the fulness of joy: and at thy right hand there is pleasure for evermore.
#+end_verse
*** Psalm 17 : Exaudi, Domine.
#+begin_verse
HEAR the right, O Lord, consider my complaint: and hearken unto my prayer, that goeth not out of feigned lips.
2 Let my sentence come forth from thy presence: and let thine eyes look upon the thing that is equal.
3 Thou hast proved and visited mine heart in the night-season; thou hast tried me, and shalt find no wickedness in me; for I am utterly purposed that my mouth shall not offend.
4 Because of men’s works, that are done against the words of thy lips: I have kept me from the ways of the destroyer.
5 O hold thou up my goings in thy paths: that my footsteps slip not.
6 I have called upon thee, O God, for thou shalt hear me: incline thine ear to me, and hearken unto my words.
7 Shew thy marvellous loving-kindness, thou that art the Saviour of them which put their trust in thee: from such as resist thy right hand.
8 Keep me as the apple of an eye: hide me under the shadow of thy wings,
9 From the ungodly that trouble me: mine enemies compass me round about to take away
my soul.
10 They are inclosed in their own fat: and their mouth speaketh proud things.
11 They lie waiting in our way on every side: turning their eyes down to the ground;
12 Like of a lion that is greedy of his prey: and as it were a lion's whelp. lurking in secret places.
13 Up, Lord, disappoint him, and cast him down: deliver my soul from the ungodly, which is a sword of thine;
14 From the men of thy hand, O Lord, from the men, I say, and from the evil world: which have their portion in this life, whose bellies thou fillest with thy hid treasure.
15 They have children at their desire: and leave the rest of their substance for their babes.
16 But as for me, I will behold thy presence in righteousness: and when I awake up after thy likeness, I shall be satisfied with it.
#+end_verse
** EVENING PRAYER
*** Psalm 18: Diligam te, Domine.
#+begin_verse
I Will love thee, O Lord, my strength; the Lord is my stony rock, and my defence: my Saviour, my God, and my might, in whom I will trust; my buckler, the horn also of my salvation, and my refuge.
2 I will call upon the Lord, which is worthy to be praised: so shall I be safe from mine enemies.
3 The sorrows of death compassed me: and the overflowings of ungodliness made me afraid.
4 The pains of hell came about me: the snares of death overtook me.
5 In my trouble I will call upon the Lord: and complain unto my God.
6 So shall he hear my voice out of his holy temple: and my complaint shall come before him, it shall enter even into his ears.
7 The earth trembled and quaked: the very foundations also of the hills shook, and were removed, because he was wroth.
8 There went a smoke out in his presence: and a consuming fire out of his mouth, so that coals were kindled at it.
9 He bowed the heavens also, and came down: and it was dark under his feet.
10 He rode upon the cherubins, and did fly: he came flying upon the wings of the wind.
11 He made darkness his secret place: his pavilion round about him, with dark water, and thick clouds to cover him.
12 At the brightness of his presence his clouds removed: hail-stones, and coals of fire.
13 The Lord also thundered out of heaven, and the Highest gave his thunder: hail-stones, and coals of fire.
14 He sent out his arrows, and scattered them: he cast forth lightnings, and destroyed them.
15 The springs of water were seen, and the foundations of the round world were discovered at thy chiding, O Lord: at the blasting of the breath of thy displeasure.
16 He shall send down from on high to fetch me: and shall take me out of many waters.
17 He shall deliver from me my strongest enemy, and from them which hate me: for they are too mighty for me.
18 They prevented me in the day of my trouble: but the Lord was my upholder.
19 He brought me forth also into a place of liberty: he brought me forth, even because he had a favour unto me.
20 The Lord shall reward me after my righteous dealing: according to the cleanness of my hands shall he recompense me.
21 Because I have kept the ways of the Lord: and have not forsaken my God, as the wicked doth.
22 For I have an eye unto all his laws: and will not cast out his commandments from me.
23 I was also uncorrupt before him: and eschewed mine own wickedness.
24 Therefore shall the Lord reward me after my righteous dealing: and according unto the cleanness of my hands in his eye-sight.
25 With the holy thou shalt be holy: and with a perfect man thou shalt be perfect.
26 With the clean thou shalt be clean: and with the froward thou shalt learn frowardness.
27 For thou shalt save the people that are in adversity: and shalt bring down the high looks of the proud.
28 Thou also shalt light my candle: the Lord my God shall make my darkness to be light.
29 For in thee I shall discomfit an host of men: and with the help of my God I shall leap over the wall.
30 The way of God is an undefiled way: the word of the Lord also is tried in the fire; he is the defender of all them that put their trust in him.
31 For who is God, but the Lord: or who hath any strength, except our God?
32 It is God, that girdeth me with strength of war: and maketh my way perfect.
33 He maketh my feet like harts feet: and setteth me up on high.
34 He teacheth mine hands to fight: and mine arms shall break even a bow of steel.
35 Thou hast given me the defence of my salvation: thy right hand also shall hold me up, and thy loving correction shall make me great.
36 Thou shalt make room enough under me for to go: that my footsteps shall not slide.
37 I will follow upon mine enemies, and overtake them: neither will I turn again till I have destroyed them.
38 I will smite them, that they shall not be able to stand: but fall under my feet.
39 Thou hast girded me with strength unto the battle: thou shalt throw done mine enemies under me.
40 Thou hast made mine enemies also to turn their backs upon me: and I shall destroy them that hate me.
41 They shall cry, but there shall be none to help them: yea, even unto the Lord shall they cry, but he shall not hear them.
42 I will beat them as small as the dust before the wind: I will cast them out as the clay in the streets.
43 Thou shalt deliver me from the strivings of the people: and thou shalt make me the head of the heathen.
44 A people whom I have not known: shall serve me.
45 As soon as they hear of me, they shall obey me: but the strange children shall dissemble with me.
46 The strange children shall fail: and be afraid out of their prisons.
47 The Lord liveth, and blessed be my strong helper: and praised be the Lord of my salvation;
48 Even the God that seeth that I be avenged: and subdueth the people unto me.
49 It is he that delivereth me from my cruel enemies, and setteth me up above mine adversaries: thou shalt rid me from the wicked man.
50 For this cause will I give thanks unto thee, O Lord, among the Gentiles: and sing praises unto thy Name.
51 Great prosperity giveth he unto his King: and sheweth loving-kindness unto David his Anointed, and unto his seed for evermore.
#+end_verse
* THE FOURTH DAY
** MORNING PRAYER
*** Psalm 19: Claw enarrant.
#+begin_verse
THE heavens declare the glory of God: and the firmament sheweth his handywork.
2 One day telleth another: and one night certifieth another.
3 There is neither speech nor language: but their voices are heard among them.
4 Their sound is gone out into all lands: and their words into the ends of the world.
5 In them hath he set a tabernacle for the sun: which cometh forth as a bridegroom out of his chamber, and rejoiceth as a giant to run his course.
6 It goeth forth from the uttermost part of the heaven, and runneth about unto the end of it again: and there is nothing hid from the heat thereof.
7 The law of the Lord is an undefiled law, converting the soul: the testimony of the Lord is sure, and giveth wisdom unto the simple.
8 The statutes of the Lord are right, and rejoice the heart: the commandment of the Lord is pure, and giveth light unto the eyes.
9 The fear of the Lord is clean, and endureth for ever: the judgments of the Lord are true, and righteous altogether.
10 More to be desired are they than gold, yea, than much fine gold: sweeter also than honey, and the honey-comb.
11 Moreover, by them is thy servant taught: and in keeping of them there is great reward.
12 Who can tell how oft he offendeth: O cleanse thou me from my secret faults.
13 Keep thy servant also from presumptuous sins, lest they get the dominion over me: so shall I be undefiled, and innocent from the great offence.
14 Let the words of my mouth, and the meditations of my heart: be alway acceptable in thy sight,
15 O Lord: my strength, and my redeemer.
#+end_verse
*** Psalm 20 : Exaudiat te Dominus.
#+begin_verse
THE Lord hear thee in the day of trouble: the Name of the God of Jacob defend thee;
2 Send thee help from the sanctuary: and strengthen thee out of Sion;
3 Remember all thy offerings: and accept thy burnt sacrifice;
4 Grant thee thy heart's desire: and fulfil all thy mind.
5 We will rejoice in thy salvation, and triumph in the Name of the Lord our God: the Lord perform all thy petitions.
6 Now know I that the Lord helpeth his Anointed, and will hear him from his holy heaven: even with the wholesome strength of
his right hand.
7 Some put their trust in chariots, and some in horses: but we will remember the Name of the Lord our God.
8 They are brought down, and fallen: but we are risen, and stand upright.
9 Save, Lord and hear us, O King of heaven: when we call upon thee.
#+end_verse

# Local Variables:
# flycheck-disabled-checkers: (proselint)
# End:

#  LocalWords:  pagebreak Beatus vir qui abiit doeth scattereth knoweth Quare
#  LocalWords:  fremuerunt dwelleth Sion Domine multiplicati smitest belongeth
#  LocalWords:  flycheck proselint invocarem makest Verba mea auribus hatest te
#  LocalWords:  defendest remembereth Deus meus sakes innocency trieth cometh
#  LocalWords:  preserveth ordaineth travaileth digged Dominus noster mightest
#  LocalWords:  visitest madest walketh Confitebor tibi judgest destructions
#  LocalWords:  maketh forgetteth liftest standest hidest speaketh abhorreth
#  LocalWords:  careth defieth sitteth lieth lurketh getteth falleth humbleth
#  LocalWords:  hideth carest beholdest mayest committeth preparest hearkeneth
#  LocalWords:  confido alloweth delighteth loveth Salvum fac minished swelleth
#  LocalWords:  Usque Dixit insipiens putteth turneth quis habitabit leadeth
#  LocalWords:  uncorrupt setteth sweareth disappointeth Conserva nightseason
#  LocalWords:  fulness Exaudi goeth inclosed fillest Diligam overflowings
#  LocalWords:  cherubins froward frowardness undefiled girdeth teacheth liveth
#  LocalWords:  strivings seeth subdueth delivereth giveth sheweth enarrant
#  LocalWords:  handywork telleth certifieth rejoiceth runneth endureth alway
#  LocalWords:  offendeth Exaudiat helpeth
